# Generated by Django 5.2.5 on 2025-08-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
