# Generated by Django 5.2.5 on 2025-08-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actuacion",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="actuacion",
            name="pedidos",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="cp",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="localidad",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="provincia",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="actuaciones",
        ),
        migrations.RemoveField(
            model_name="factura",
            name="serie",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="presupuesto",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="presupuesto",
            name="numero",
        ),
        migrations.RemoveField(
            model_name="presupuesto",
            name="observaciones",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cif",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="color_primario",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="cp",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="direccion",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="fuente_factura",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="inicio_serie_facturas",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="localidad",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="notas_factura",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="pie_factura",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="provincia",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="rol",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="serie_facturas",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="web",
        ),
        migrations.AddField(
            model_name="actuacion",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.pedido",
            ),
        ),
        migrations.AddField(
            model_name="actuacion",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="factura",
            name="actuacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.actuacion",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="descripcion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pedido",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="concepto",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="actuacion",
            name="descripcion",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cliente",
            name="cif",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[
                    ("borrador", "Borrador"),
                    ("enviado", "Enviado"),
                    ("pagado", "Pagado"),
                ],
                default="borrador",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero",
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name="Producto",
        ),
    ]
