# Generated by Django 5.2.5 on 2025-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_factura_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cif",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
