# Generated by Django 5.2.5 on 2025-08-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_actuacion_usuario_alter_cliente_usuario_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cliente",
            index=models.Index(
                fields=["usuario"], name="core_client_usuario_4dd5d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["usuario"], name="core_factur_usuario_e0786f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedido",
            index=models.Index(
                fields=["usuario"], name="core_pedido_usuario_c0a4c9_idx"
            ),
        ),
    ]
