# Generated by Django 5.2.5 on 2025-08-07 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cliente_core_client_usuario_4dd5d5_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cif",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z0-9]{1,20}$", "CIF inválido"
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="cliente",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("cif__isnull", True), _negated=True),
                    models.Q(("cif", ""), _negated=True),
                ),
                fields=("cif",),
                name="unique_cif_nonblank",
            ),
        ),
    ]
