# Generated by Django 5.2.5 on 2025-08-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pedidos", "0001_initial"),
        ("presupuestos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="presupuesto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="presupuestos.presupuesto",
            ),
        ),
    ]
