# Generated by Django 5.2.5 on 2025-08-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actuaciones", "0002_initial"),
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("numero", models.CharField(max_length=20, unique=True)),
                (
                    "base_imponible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=21.0, max_digits=5),
                ),
                (
                    "irpf",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("pagado", "Pagado"),
                        ],
                        default="borrador",
                        max_length=20,
                    ),
                ),
                (
                    "actuacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="actuaciones.actuacion",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
