# Generated by Django 5.2.5 on 2025-08-07 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actuaciones", "0002_initial"),
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="actuacion",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actuaciones",
                to="pedidos.pedido",
            ),
        ),
    ]
